# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            John Burke
tagline:          'Coding, Conlangs, and Catholicism'
description:      'Come explore processors, security, software, and conlangs with me. There is a fun in the mingling and meandering'
url:              http://hyde.getpoole.com
baseurl:          /

author:
  name:           'John S. Burke'
  url:            https://github.com/jsburke

paginate:         1

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jsburke/jsburke.github.io
